pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
                echo 'repo checkout success'
            }
        }
        stage('lsit files'){
            steps{
                bat 'dir'
            }
        }
    }
}