plugins{
    agent any
    stages{
        stage('build'){
            steps{
                bat 'mvn compile'
            }
        }
        stage('test'){
            steps{
                bat 'mvn test'
            }
        }
        stage('package'){
            steps{
                bat 'mvn package'
            }
        }
    }
}