pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('maven/student-app') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('maven/student-app') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('maven/student-app') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}