pipeline{
    agent any
    stages{
        stage('build'){
            steps{
                dir('library-system'){
                    bat 'mvn clean'
                }
            }
        }
        stage('test'){
            steps{
                dir('library-system'){
                    bat 'mvn test'
                }
            }
        }
        stage('package'){
            steps{
                dir('library-system'){
                    bat 'mvn package'
                }
            }
        }
    }
}